### ISSUE TITLE
Nothing

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#1]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docsconcepts/policies-and-telemetry/_index.md) [原文页面](https://preliminary.istio.io/docs/concepts/policies-and-telemetry/_index.md)

**Comment by rootsongjc** [comment]
What is this issue do with?

**Comment by fleeto** [comment]
chatbot

**Comment by rootsongjc** [comment]
Just for chatbot testing.
