### ISSUE TITLE
/docs/reference/glossary/virtual-service.md

### ISSUE THREAD

**Issue by SataQiu** [servicemesher/istio-official-translation#1271]
Source File: [/docs/reference/glossary/virtual-service.md](https://github.com/istio/istio.io/tree/master/content/en/docs/reference/glossary/virtual-service.md)

**Comment by GuangmingLuo** [comment]
@SataQiu 
frankbu and istio-testing Remove virtual service from glossary (#6088) 4 days ago

**Comment by SataQiu** [comment]
Thanks @GuangmingLuo
