### ISSUE TITLE
/docs/setup/upgrade/cni-helm-upgrade/index.md

### ISSUE THREAD

**Issue by SataQiu** [servicemesher/istio-official-translation#1383]
Source File: [/docs/setup/upgrade/cni-helm-upgrade/index.md](https://github.com/istio/istio.io/tree/master/content/en/docs/setup/upgrade/cni-helm-upgrade/index.md)

**Comment by donychen1134** [comment]
求助：
1. The upgrade process may install new binaries and may change configuration and API schemas.
  这里的 API schemas 该如何翻译呢？
2. If you installed Istio CNI using Helm and Tiller, the preferred upgrade option is to let Helm take care of the upgrade.
  这里的 Helm and Tiller 需要翻译吗？还是直接用 Helm and Tiller 就行呢？
3. Pilot, Galley, Policy, Telemetry and Sidecar injector. Choose one of the following mutually exclusive options to update the control plane.
  这句这样翻译会不会有点生硬：Pilot, Galley, 策略, 遥测和 Sidecar 注入器。选择下列 **互斥** 选项中的一种升级控制平面。
4. including configurations generated using helm template.
  helm template 需要翻译吗？这样翻译可以么：包括使用 [Helm template](/docs/setup/install/helm/#option-1-install-with-helm-via-helm-template) 生成的配置。
5. The rolling update process will upgrade all deployments and configmaps to the new version.
  deployments and configmaps 该如何翻译呢？这样翻译可以么：滚动更新进程会将所有的部署组件和配置升级到新版本。
6. Upgrade the istio-init chart to update all the Istio Custom Resource Definitions (CRDs)
  这里的 chart 需要翻译么？这样翻译可以么：升级 `istio-init` chart 来更新所有 Istio [用户资源定义](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#customresourcedefinitions)（CRD）

**Comment by donychen1134** [comment]
/pushed

> 求助：
> 
> 1. The upgrade process may install new binaries and may change configuration and API schemas.
>    这里的 API schemas 该如何翻译呢？
> 2. If you installed Istio CNI using Helm and Tiller, the preferred upgrade option is to let Helm take care of the upgrade.
>    这里的 Helm and Tiller 需要翻译吗？还是直接用 Helm and Tiller 就行呢？
> 3. Pilot, Galley, Policy, Telemetry and Sidecar injector. Choose one of the following mutually exclusive options to update the control plane.
>    这句这样翻译会不会有点生硬：Pilot, Galley, 策略, 遥测和 Sidecar 注入器。选择下列 **互斥** 选项中的一种升级控制平面。
> 4. including configurations generated using helm template.
>    helm template 需要翻译吗？这样翻译可以么：包括使用 [Helm template](/docs/setup/install/helm/#option-1-install-with-helm-via-helm-template) 生成的配置。
> 5. The rolling update process will upgrade all deployments and configmaps to the new version.
>    deployments and configmaps 该如何翻译呢？这样翻译可以么：滚动更新进程会将所有的部署组件和配置升级到新版本。
> 6. Upgrade the istio-init chart to update all the Istio Custom Resource Definitions (CRDs)
>    这里的 chart 需要翻译么？这样翻译可以么：升级 `istio-init` chart 来更新所有 Istio [用户资源定义](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#customresourcedefinitions)（CRD）

先按我自己的理解进行了翻译，这些是可能存在问题的点，先做个标记。
