### ISSUE TITLE
关于英文路径与中文路径不一致问题

### ISSUE THREAD

**Issue by huntsman-li** [servicemesher/istio-official-translation#1450]
- 问题
经过翻译，发现content/zh/docs/tasks/security 和 content/en/docs/tasks/security 下的内容不一致，这个问题是否会导致其他问题，是否需要校准
![image](https://user-images.githubusercontent.com/36752240/68558034-c3718100-0472-11ea-9425-9a33d4252395.png)
![image](https://user-images.githubusercontent.com/36752240/68558046-cff5d980-0472-11ea-9753-97fc4d298950.png)

**Comment by TomatoAres** [comment]
@huntsman-li 我遇到同样的问题，这个你是怎么处理了？

**Comment by tanjunchen** [comment]
@huntsman-li @TomatoAres  这个问题已经得到解决，并且引入了CI机制，如果 zh/ 下的引用了 en/ 中的文件会报错。可参考  https://github.com/istio/istio.io/pull/5823 。 所以，close issue
/close
