### ISSUE TITLE
/docs/ops/prep/_index.md

### ISSUE THREAD

**Issue by SataQiu** [servicemesher/istio-official-translation#1475]
Source File: [/docs/ops/prep/_index.md](https://github.com/istio/istio.io/tree/master/content/en/docs/ops/prep/_index.md)

**Comment by tanjunchen** [comment]
/close
broken url

**Comment by tanjunchen** [comment]
/close
the url is broken
@rootsongjc

**Comment by tanjunchen** [comment]
/close
the url is broken
@rootsongjc
