### ISSUE TITLE
/docs/ops/prep/deployment-models/index.md

### ISSUE THREAD

**Issue by SataQiu** [servicemesher/istio-official-translation#1476]
Source File: [/docs/ops/prep/deployment-models/index.md](https://github.com/istio/istio.io/tree/master/content/en/docs/ops/prep/deployment-models/index.md)

**Comment by helight** [comment]
@malphi this should be /docs/ops/deployment/deployment-models/index.md ?

**Comment by gauliang** [comment]
原文已经不在可以关闭了

**Comment by gauliang** [comment]
> Source File: [/docs/ops/prep/deployment-models/index.md](https://github.com/istio/istio.io/tree/master/content/en/docs/ops/prep/deployment-models/index.md)
to
> Source File: [docs/ops/deployment/deployment-models/index.md](https://github.com/istio/istio.io/tree/master/content/en/docs/ops/deployment/deployment-models/index.md)
