### ISSUE TITLE
content/zh/news/ 目录需要重新初始化

### ISSUE THREAD

**Issue by GuangmingLuo** [servicemesher/istio-official-translation#1608]
content/zh/news/  与 content/en/news/ 目录结构不一致，需要重新初始化

**Comment by gauliang** [comment]
现在看，Master 分支上两个目录结构是一致的，只是内容需要翻译。
@GuangmingLuo

**Comment by rootsongjc** [comment]
既然目录结构都一直了，那这个 issue 是不是可以关闭了？

**Comment by gauliang** [comment]
关了吧

**Comment by GuangmingLuo** [comment]
如果确认目录结构一致，这个issue可以关闭了。

**Comment by gauliang** [comment]
目录结构一致，不过现在 en 下又新增了几个文件，我提交个 PR 吧。
