### ISSUE TITLE
/events/index.md

### ISSUE THREAD

**Issue by SataQiu** [servicemesher/istio-official-translation#1652]
Source File: [/events/index.md](https://github.com/istio/istio.io/tree/master/content/en/events/index.md)

**Comment by gauliang** [comment]
这一类的页面怎么预览效果？

**Comment by rootsongjc** [comment]
这种页面不是直接显示的单页，而是作为页面的一个组成模块，建议你同时认领该目录下的其他issue组合来看。

**Comment by gauliang** [comment]
好的
