### ISSUE TITLE
关于 release note 术语格式的讨论

### ISSUE THREAD

**Issue by gorda** [servicemesher/istio-official-translation#1667]
## 写在前面

目前 [约定和术语表](https://github.com/servicemesher/istio-official-translation/blob/master/term.md) 没有规范 `release note` 部分的风格。

鉴于 `release note` 存在大量高频的词汇，但是同学们的理解不同，翻译的结果也有所不同，现在希望大家参考讨论，统一部分术语的翻译，最终呈现出一份规范的译文。

对于频繁出现的词汇，大家可以将其发列出，并附上个人翻译建议，大家共同讨论。

格式参考 [常见词汇](https://github.com/servicemesher/istio-official-translation/blob/master/term.md#%E5%B8%B8%E7%94%A8%E8%AF%8D%E6%B1%87) 例如：

- release note：发行说明

## 术语列表

我先列出部分已知的常见词汇及个人看法，欢迎大家参与讨论完善。

- release note：发行说明
- Announcing Istio x.x.x：Istio x.x.x 发布公告
- Istio x.x.x announcement.：Istio x.x.x 公告
- Istio x.x.x patch release.：Istio x.x.x 补丁发布

- Major Update：重大更新
- General：概况
- Known issues：已知问题
- Security：安全
- Security update：安全更新
- Other：其它
- Miscellaneous：杂项
- Bug fixes：Bug 修复
- Small enhancements：小的改进
- minor enhancements：小的增强
- Affected Istio releases：受影响的 Istio 版本
- Vulnerability impact：漏洞影响
- Mitigation：防范
- Behavior change：行为变更
- Features：特性/特征
- New：新增
- Add：添加
- Modified：修改
- Removed：移除

## 2019-12-21 新增

- operator：运维人员

**Comment by malphi** [comment]
个人觉得没有问题，可以加到约定里。

**Comment by rootsongjc** [comment]
那些有两个选项的就统一为下面的翻译吧。
release note：发行说明
Major Update：重大更新
General：概况
Other：其它
Miscellaneous：杂项
Security update：安全更新
Bug fixes：Bug 修复
Small enhancements：小的改进
minor enhancements：小的增强
Features：特性/特征
New：新增
Removed：移除

**Comment by ilylia** [comment]
没问题

**Comment by GuangmingLuo** [comment]
Small enhancements 与 minor enhancements 需要区分开来么？

**Comment by helight** [comment]
没问题，挺好的，赞

**Comment by kaleocheng** [comment]
我看到有 [ 约定和术语表 ](https://github.com/servicemesher/istio-official-translation/blob/master/term.md) ，但我想我们可以把所有的术语放到一个 json 或者 csv ，方便本地翻译的时候使用工具来自动化替换

**Comment by gorda** [comment]
> Small enhancements 与 minor enhancements 需要区分开来么？

我也感觉没啥区别😂

**Comment by gorda** [comment]
> 我看到有 [ 约定和术语表 ](https://github.com/servicemesher/istio-official-translation/blob/master/term.md) ，但我想我们可以把所有的术语放到一个 json 或者 csv ，方便本地翻译的时候使用工具来自动化替换

听起来似乎很不错
