### ISSUE TITLE
performance-and-scalability/microbenchmarks.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#17]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/performance-and-scalability/microbenchmarks/index.md) [原文页面](https://preliminary.istio.io/docs/performance-and-scalability/microbenchmarks)

**Comment by xiaosuiba** [comment]
认领

**Comment by xiaosuiba** [comment]
[PR](https://github.com/istio/istio.github.io/pull/1656) send.

**Comment by rootsongjc** [comment]
已翻译完成，见 https://preliminary.istio.io/zh/docs/setup/kubernetes/ansible-install
