### ISSUE TITLE
/about/contribute/terminology/index.md

### ISSUE THREAD

**Issue by SataQiu** [servicemesher/istio-official-translation#1773]
Source File: [/about/contribute/terminology/index.md](https://github.com/istio/istio.io/tree/master/content/en/about/contribute/terminology/index.md)

**Comment by helight** [comment]
@rootsongjc  @SataQiu 这些文档还没有同步到中文目录，我同步提交一次？

**Comment by rootsongjc** [comment]
@helight 好的，辛苦了。

**Comment by SataQiu** [comment]
Sorry @rootsongjc, only issues with special values ('pushed') can be accepted.
