### ISSUE TITLE
sync new files to about/contribute/

### ISSUE THREAD

**Issue by helight** [servicemesher/istio-official-translation#1795]
sync new files to about/contribute/

Source File: [/about/contribute/](https://github.com/istio/istio.io/tree/master/content/en/about/contribute)
those are new files:

	content/zh/about/contribute/build/
	content/zh/about/contribute/code-blocks/
	content/zh/about/contribute/formatting/
	content/zh/about/contribute/front-matter/
	content/zh/about/contribute/shortcodes/
	content/zh/about/contribute/terminology/

**Comment by SataQiu** [comment]
Sorry @helight, only issues with special values ('pending') can be accepted.
