### ISSUE TITLE
/blog/2020/tradewinds-2020/index.md

### ISSUE THREAD

**Issue by helight** [servicemesher/istio-official-translation#1796]
source file : [/blog/2020/tradewinds-2020/index.md](https://github.com/istio/istio.io/blob/master/content/en/blog/2020/tradewinds-2020/index.md)

**Comment by SataQiu** [comment]
Sorry @helight, only issues with special values ('pending') can be accepted.

**Comment by SataQiu** [comment]
Sorry @helight, only issues with special values ('pending') can be accepted.

**Comment by SataQiu** [comment]
Sorry @helight, only issues had been assigned can be accepted.
