### ISSUE TITLE
content/docs/examples/advanced-egress/egress-tls-origination/index.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#182]
文件路径：content/docs/examples/advanced-egress/egress-tls-origination/index.md

[源码](https://github.com/istio/istio.github.io/tree/master/content/docs/examples/advanced-egress/egress-tls-origination/index.md)

[网址](https://istio.io//docs/examples/advanced-egress/egress-tls-origination/index.htm)

**Comment by DavadDi** [comment]
路径调整为 https://github.com/istio/istio.github.io/blob/master/content/docs/examples/advanced-gateways/_index.md

**Comment by DavadDi** [comment]
@fleeto  这个文档是新的需要还是文档内容有更新？ 中文目录中已经翻译过了这篇文档

**Comment by DavadDi** [comment]
中文地址：https://github.com/istio/istio.github.io/blob/master/content_zh/docs/examples/advanced-gateways/egress-tls-origination/index.md
