### ISSUE TITLE
performance-and-scalability/performance-testing-automation.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#19]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/performance-and-scalability/performance-testing-automation/index.md) [原文页面](https://preliminary.istio.io/docs/performance-and-scalability/performance-testing-automation)

**Comment by xiaosuiba** [comment]
[PR](https://github.com/istio/istio.github.io/pull/1657) send.

**Comment by rootsongjc** [comment]
翻译完成，见 https://preliminary.istio.io/zh/docs/concepts/performance-and-scalability/
