### ISSUE TITLE
concepts/policies-and-telemetry/_index.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#2]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/concepts/policies-and-telemetry/_index.md) [原文页面](https://preliminary.istio.io/docs/concepts/policies-and-telemetry/)

**Comment by rootsongjc** [comment]
翻译完成，见 https://preliminary.istio.io/zh/docs/concepts/policies-and-telemetry/
