### ISSUE TITLE
performance-and-scalability/realistic-app-benchmark.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#20]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/performance-and-scalability/realistic-app-benchmark/index.md) [原文页面](https://preliminary.istio.io/docs/performance-and-scalability/realistic-app-benchmark)

**Comment by xiaosuiba** [comment]
[PR](https://github.com/istio/istio.github.io/pull/1658) send.
