### ISSUE TITLE
部署模型章节的一些建议

### ISSUE THREAD

**Issue by kentchenjh** [servicemesher/istio-official-translation#2013]
在阅读部署模型章节(<https://istio.io/latest/zh/docs/ops/deployment/deployment-models>)时遇到一点小问题。

1. 
译文：团队或项目隔离：每个团队仅运行自己的集集群。
建议：集集群，笔误，改为集群。

2. 
译文：则中断范围仅限于该控制平面。
原文：the scope of the outage is limited to only that control plane.
建议：中断范围有些奇怪，改为不可用范围是否好些。

3. 
译文：以及用于识别网格及网格联邦中所有身份 信息的 trust bundle
建议： 所有身份 信息，多了空格。

**Comment by rootsongjc** [comment]
你好，感谢反馈，您可以提交一个 PR 来修复以上问题。

**Comment by gauliang** [comment]
我来处理一下巴
