### ISSUE TITLE
performance-and-scalability/scalability.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#21]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/performance-and-scalability/scalability/index.md) [原文页面](https://preliminary.istio.io/docs/performance-and-scalability/scalability)

**Comment by xiaosuiba** [comment]
认领

**Comment by xiaosuiba** [comment]
[PR](https://github.com/istio/istio.github.io/pull/1663) send.

**Comment by rootsongjc** [comment]
原文已移动和合并，该 issue 不再追踪，翻译已完成，见 https://preliminary.istio.io/zh/docs/concepts/performance-and-scalability/
