### ISSUE TITLE
performance-and-scalability/scenarios.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#22]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/performance-and-scalability/scenarios/index.md) [原文页面](https://preliminary.istio.io/docs/performance-and-scalability/scenarios)

**Comment by xiaosuiba** [comment]
认领

**Comment by xiaosuiba** [comment]
[PR](https://github.com/istio/istio.github.io/pull/1664) send.
