### ISSUE TITLE
performance-and-scalability/synthetic-benchmarks.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#23]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/performance-and-scalability/synthetic-benchmarks/index.md) [原文页面](https://preliminary.istio.io/docs/performance-and-scalability/synthetic-benchmarks)

**Comment by xiaosuiba** [comment]
认领

**Comment by xiaosuiba** [comment]
[PR](https://github.com/istio/istio.github.io/pull/1671) send.
/pushed

**Comment by xiaosuiba** [comment]
[PR](https://github.com/istio/istio.github.io/pull/1671) send.
