### ISSUE TITLE
content/help/glossary/workload-principal.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#266]
文件路径：content/help/glossary/workload-principal.md

[源码](https://github.com/istio/istio.github.io/tree/master/content/help/glossary/workload-principal.md)

[网址](https://istio.io//help/glossary/workload-principal.htm)

**Comment by trainyao** [comment]
这个英文稿件已经不存在

**Comment by trainyao** [comment]
上面这个push是为了解开3个translating限制。。。。没法accpet其他issue了

**Comment by rootsongjc** [comment]
原文已不存在，关闭该issue并停止追踪。
