### ISSUE TITLE
content/help/ops/security/authorization-permissive/index.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#274]
文件路径：content/help/ops/security/authorization-permissive/index.md

[源码](https://github.com/istio/istio.github.io/tree/master/content/help/ops/security/authorization-permissive/index.md)

[网址](https://istio.io//help/ops/security/authorization-permissive/index.htm)

**Comment by xionchen** [comment]
https://github.com/istio/istio.github.io/pull/2241
