### ISSUE TITLE
concepts/policies-and-telemetry/config.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#3]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/concepts/policies-and-telemetry/config/index.md) [原文页面](https://preliminary.istio.io/docs/concepts/policies-and-telemetry/config) 

[译文代码](https://github.com/doczhcn/istio/tree/master/docs/concepts/policy-and-control/mixer-config.md) [译文页面](http://istio.doczh.cn/docs/concepts/policy-and-control/mixer-config.html)

**Comment by rootsongjc** [comment]
认领

**Comment by rootsongjc** [comment]
已提交PR，https://github.com/istio/istio.github.io/pull/1659，因CI问题未通过

**Comment by rootsongjc** [comment]
已合并到上游，关闭issue。
