### ISSUE TITLE
reference/config/policy-and-telemetry/metrics.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#30]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/reference/config/policy-and-telemetry/metrics.md) [原文页面](https://preliminary.istio.io/docs/reference/config/policy-and-telemetry/metrics)

**Comment by xiaosuiba** [comment]
[PR](https://github.com/istio/istio.github.io/pull/1689) send.
/pushed

**Comment by fleeto** [comment]
只能用一个指令，啥都不能加

**Comment by xiaosuiba** [comment]
[PR](https://github.com/istio/istio.github.io/pull/1689) send.

**Comment by rootsongjc** [comment]
已翻译完成，见 https://preliminary.istio.io/zh/docs/reference/config/policy-and-telemetry/metrics
