### ISSUE TITLE
reference/config/policy-and-telemetry/templates/_index.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#31]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/reference/config/policy-and-telemetry/templates/_index.md) [原文页面](https://preliminary.istio.io/docs/reference/config/policy-and-telemetry/templates/)

**Comment by fuxu** [comment]
我可以先拿这个简单的index页面练练手
