### ISSUE TITLE
setup/kubernetes/ansible-install.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#38]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/setup/kubernetes/ansible-install/index.md) [原文页面](https://preliminary.istio.io/docs/setup/kubernetes/ansible-install)

**Comment by xiaosuiba** [comment]
认领

**Comment by rootsongjc** [comment]
已翻译完成，见 https://preliminary.istio.io/zh/docs/reference/config/policy-and-telemetry/metrics
