### ISSUE TITLE
setup/kubernetes/helm-install.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#39]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/setup/kubernetes/helm-install/index.md) [原文页面](https://preliminary.istio.io/docs/setup/kubernetes/helm-install)

**Comment by xiaosuiba** [comment]
认领

**Comment by xiaosuiba** [comment]
[PR](https://github.com/istio/istio.github.io/pull/1651) send.

**Comment by rootsongjc** [comment]
翻译完成，见 https://preliminary.istio.io/zh/docs/setup/kubernetes/helm-install
