### ISSUE TITLE
concepts/policies-and-telemetry/overview.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#4]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/concepts/policies-and-telemetry/overview/index.md) [原文页面](https://preliminary.istio.io/docs/concepts/policies-and-telemetry/overview) 

[译文代码](https://github.com/doczhcn/istio/tree/master/docs/concepts/policy-and-control/overview.md) [译文页面](http://istio.doczh.cn/docs/concepts/policy-and-control/overview.html)

**Comment by rootsongjc** [comment]
Translation complete.

**Comment by rootsongjc** [comment]
该文件已经被删除，与另一篇文档合并，因此该Issue不再追踪。见https://github.com/servicemesher/istio-official-translation/issues/113
