### ISSUE TITLE
setup/kubernetes/quick-start.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#42]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/setup/kubernetes/quick-start/index.md) [原文页面](https://preliminary.istio.io/docs/setup/kubernetes/quick-start) 

[译文代码](https://github.com/doczhcn/istio/tree/master/docs/setup/kubernetes/quick-start.md) [译文页面](http://istio.doczh.cn/docs/setup/kubernetes/quick-start.html)

**Comment by rootsongjc** [comment]
已翻译完成
