### ISSUE TITLE
setup/kubernetes/upgrading-istio.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#45]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/setup/kubernetes/upgrading-istio/index.md) [原文页面](https://preliminary.istio.io/docs/setup/kubernetes/upgrading-istio)

**Comment by xiaosuiba** [comment]
认领

**Comment by xiaosuiba** [comment]
[PR](https://github.com/istio/istio.github.io/pull/1650) send.

**Comment by rootsongjc** [comment]
翻译完成，见 https://preliminary.istio.io/zh/docs/setup/kubernetes/upgrading-istio
