### ISSUE TITLE
tasks/security/health-check.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#51]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/tasks/security/health-check/index.md) [原文页面](https://preliminary.istio.io/docs/tasks/security/health-check)

**Comment by xieydd** [comment]
认领

**Comment by xieydd** [comment]
@fleeto  Can you assigned this to others, I am interested wit another ,but i have no much time sorry.
