### ISSUE TITLE
tasks/security/https-overlay.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#52]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/tasks/security/https-overlay/index.md) [原文页面](https://preliminary.istio.io/docs/tasks/security/https-overlay)

**Comment by xieydd** [comment]
认领

**Comment by rootsongjc** [comment]
已翻译完成，见 https://preliminary.istio.io/zh/docs/tasks/security/https-overlay
