### ISSUE TITLE
tasks/security/plugin-ca-cert.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#54]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/tasks/security/plugin-ca-cert/index.md) [原文页面](https://preliminary.istio.io/docs/tasks/security/plugin-ca-cert) 

[译文代码](https://github.com/doczhcn/istio/tree/master/docs/tasks/security/plugin-ca-cert.md) [译文页面](http://istio.doczh.cn/docs/tasks/security/plugin-ca-cert.html)

**Comment by rootsongjc** [comment]
https://github.com/istio/istio.github.io/pull/1652 /merged
