### ISSUE TITLE
tasks/security/role-based-access-control.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#55]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/tasks/security/role-based-access-control/index.md) [原文页面](https://preliminary.istio.io/docs/tasks/security/role-based-access-control) 

[译文代码](https://github.com/doczhcn/istio/tree/master/docs/tasks/security/role-based-access-control.md) [译文页面](http://istio.doczh.cn/docs/tasks/security/role-based-access-control.html)

**Comment by huhaifan** [comment]
认领

**Comment by rootsongjc** [comment]
@huhaifan 请先加入到ServiceMesher的GitHub组织里，然后可以领取任务。我已经发送了邀请，请检查你的邮箱。

**Comment by huhaifan** [comment]
已加入
