### ISSUE TITLE
tasks/telemetry/fluentd.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#59]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/tasks/telemetry/fluentd/index.md) [原文页面](https://preliminary.istio.io/docs/tasks/telemetry/fluentd) 

[译文代码](https://github.com/doczhcn/istio/tree/master/docs/tasks/telemetry/fluentd.md) [译文页面](http://istio.doczh.cn/docs/tasks/telemetry/fluentd.html)

**Comment by pigletfly** [comment]
merge request sent https://github.com/istio/istio.github.io/pull/1631

**Comment by rootsongjc** [comment]
[istio/istio.github.io#1631](https://github.com/istio/istio.github.io/pull/1631) 被关闭需要重新提交
