### ISSUE TITLE
纰漏 多处 host 应为hosts

### ISSUE THREAD

**Issue by acteq** [servicemesher/istio-official-translation#593]
源: https://github.com/istio/istio.io/blob/master/content_zh/docs/concepts/traffic-management/index.md
文档 https://preliminary.istio.io/zh/docs/concepts/traffic-management/
例如
规则的目标描述
路由规则对应着一或多个用 VirtualService 配置指定的请求目的主机。这些主机可以是也可以不是实际的目标负载，甚至可以不是同一网格内可路由的服务。例如要给到 reviews 服务的请求定义路由规则，可以使用内部的名称 reviews，也可以用域名 bookinfo.com，VirtualService 可以定义这样的 host 字段：

hosts:
  - reviews
  - bookinfo.com

**Comment by rootsongjc** [comment]
@acteq 感谢反馈，请[联系我](https://jimmysong.io/about)加入 ServiceMesher 社区后向 Istio 官网仓库提交 PR 修复该问题。
