### ISSUE TITLE
content/help/faq/telemetry/no-tracing.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#595]
文件路径：content/help/faq/telemetry/no-tracing.md

[源码](https://github.com/istio/istio.github.io/tree/master/content/help/faq/telemetry/no-tracing.md)

[网址](https://istio.io//help/faq/telemetry/no-tracing.htm)

**Comment by SataQiu** [comment]
PR, istio/istio.io#2971
