### ISSUE TITLE
tasks/telemetry/querying-metrics.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#61]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/tasks/telemetry/querying-metrics/index.md) [原文页面](https://preliminary.istio.io/docs/tasks/telemetry/querying-metrics) 

[译文代码](https://github.com/doczhcn/istio/tree/master/docs/tasks/telemetry/querying-metrics.md) [译文页面](http://istio.doczh.cn/docs/tasks/telemetry/querying-metrics.html)

**Comment by pigletfly** [comment]
认领
