### ISSUE TITLE
tasks/traffic-management/_index.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#65]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/tasks/traffic-management/_index.md) [原文页面](https://preliminary.istio.io/docs/tasks/traffic-management/)

**Comment by loverto** [comment]
认领

**Comment by loverto** [comment]
[PR](https://github.com/istio/istio.github.io/pull/1665)

**Comment by loverto** [comment]
已提交

**Comment by rootsongjc** [comment]
文档有更新，请检查更新。

**Comment by loverto** [comment]
这个没变啊

**Comment by rootsongjc** [comment]
我写错地方了，这篇文档是个目录，没有更改，关闭issue.
