### ISSUE TITLE
tasks/traffic-management/app-health-check.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#66]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/tasks/traffic-management/app-health-check/index.md) [原文页面](https://preliminary.istio.io/docs/tasks/traffic-management/app-health-check)

**Comment by xiaosuiba** [comment]
认领

**Comment by xiaosuiba** [comment]
[PR](https://github.com/istio/istio.github.io/pull/1633) send.
