### ISSUE TITLE
concepts/security/mutual-tls.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#7]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/concepts/security/mutual-tls/index.md) [原文页面](https://preliminary.istio.io/docs/concepts/security/mutual-tls) 

[译文代码](https://github.com/doczhcn/istio/tree/master/docs/concepts/security/mutual-tls.md) [译文页面](http://istio.doczh.cn/docs/concepts/security/mutual-tls.html)

**Comment by rootsongjc** [comment]
https://github.com/istio/istio.github.io/pull/1660 /merged
