### ISSUE TITLE
tasks/traffic-management/ingress.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#71]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/tasks/traffic-management/ingress/index.md) [原文页面](https://preliminary.istio.io/docs/tasks/traffic-management/ingress) 

[译文代码](https://github.com/doczhcn/istio/tree/master/docs/tasks/traffic-management/ingress.md) [译文页面](http://istio.doczh.cn/docs/tasks/traffic-management/ingress.html)

**Comment by loverto** [comment]
认领

**Comment by loverto** [comment]
[PR](https://github.com/istio/istio.github.io/pull/1665)

**Comment by loverto** [comment]
已提交

**Comment by rootsongjc** [comment]
https://github.com/istio/istio.github.io/pull/1681 已合并。
