### ISSUE TITLE
/help/faq/metrics-and-logs/controlling-what-the-sidecar-reports.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#711]
Source File: [/help/faq/metrics-and-logs/controlling-what-the-sidecar-reports.md](https://github.com/istio/istio.io/tree/master/content/help/faq/metrics-and-logs/controlling-what-the-sidecar-reports.md)

**Comment by SataQiu** [comment]
PR, istio/istio.io#3288
