### ISSUE TITLE
tasks/traffic-management/mirroring.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#72]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/tasks/traffic-management/mirroring/index.md) [原文页面](https://preliminary.istio.io/docs/tasks/traffic-management/mirroring) 

[译文代码](https://github.com/doczhcn/istio/tree/master/docs/tasks/traffic-management/mirroring.md) [译文页面](http://istio.doczh.cn/docs/tasks/traffic-management/mirroring.md)

**Comment by KingArtherTT** [comment]
认领

**Comment by KingArtherTT** [comment]
[new Pull Request](https://github.com/doczhcn/istio/pull/142)

**Comment by rootsongjc** [comment]
@KingArtherTT 你提交错 repo 了，应该提交到这里 https://github.com/istio/istio.github.io

**Comment by KingArtherTT** [comment]
pull request: https://github.com/istio/istio.github.io/pull/1868

请问是 直接往这儿提吗？@rootsongjc

**Comment by rootsongjc** [comment]
是的，不过你需要先签署CLA才能提交。

**Comment by KingArtherTT** [comment]
new pull request:https://github.com/istio/istio.github.io/pull/1870
已经签署了CLA。

**Comment by rootsongjc** [comment]
已合并，见 https://preliminary.istio.io/zh/docs/tasks/traffic-management/mirroring
