### ISSUE TITLE
tasks/traffic-management/request-routing.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#73]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/tasks/traffic-management/request-routing/index.md) [原文页面](https://preliminary.istio.io/docs/tasks/traffic-management/request-routing) 

[译文代码](https://github.com/doczhcn/istio/tree/master/docs/tasks/traffic-management/request-routing.md) [译文页面](http://istio.doczh.cn/docs/tasks/traffic-management/request-routing.html)

**Comment by zhaohuabing** [comment]
认领

**Comment by zhaohuabing** [comment]
WIP https://github.com/istio/istio.github.io/pull/1654
