### ISSUE TITLE
tasks/traffic-management/request-timeouts.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#74]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/tasks/traffic-management/request-timeouts/index.md) [原文页面](https://preliminary.istio.io/docs/tasks/traffic-management/request-timeouts) 

[译文代码](https://github.com/doczhcn/istio/tree/master/docs/tasks/traffic-management/request-timeouts.md) [译文页面](http://istio.doczh.cn/docs/tasks/traffic-management/request-timeouts.html)

**Comment by KingArtherTT** [comment]
小弟认领了

**Comment by KingArtherTT** [comment]
认领

**Comment by KingArtherTT** [comment]
have committed directly to the master branch.
