### ISSUE TITLE
tasks/traffic-management/traffic-shifting.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#75]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/tasks/traffic-management/traffic-shifting/index.md) [原文页面](https://preliminary.istio.io/docs/tasks/traffic-management/traffic-shifting) 

[译文代码](https://github.com/doczhcn/istio/tree/master/docs/tasks/traffic-management/traffic-shifting.md) [译文页面](http://istio.doczh.cn/docs/tasks/traffic-management/traffic-shifting.html)

**Comment by zhaohuabing** [comment]
认领

**Comment by zhaohuabing** [comment]
WIP https://github.com/istio/istio.github.io/pull/1632

**Comment by rootsongjc** [comment]
已翻译完成，见 https://preliminary.istio.io/zh/docs/tasks/traffic-management/traffic-shifting
