### ISSUE TITLE
让测试的镜像地址更容易下载

### ISSUE THREAD

**Issue by loverto** [servicemesher/istio-official-translation#76]
把测试的docker镜像替换为`gcr.mirrors.ustc.edu.cn/istio-testing/website-builder:2018-06-15`

**Comment by rootsongjc** [comment]
大家可以下载该镜像后使用`docker tag`将其重命名为`Makefile`里面的镜像名称`gcr.io/istio-testing/website-builder:2018-06-15`，这样就可以顺利的执行`make lint`了。执行下面的命令：
```bash
docker pull gcr.mirrors.ustc.edu.cn/istio-testing/website-builder:2018-06-15
docker tag gcr.mirrors.ustc.edu.cn/istio-testing/website-builder:2018-06-15 gcr.io/istio-testing/website-builder:2018-06-15
```
