### ISSUE TITLE
翻译约定和术语表

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/istio-official-translation#77]
为了便于大家达成共识，以下为Istio官方文档的翻译约定和词汇术语表。
## 术语表

请参考[Service Mesh术语表](https://github.com/servicemesher/istio-official-translation/blob/master/term.md)。

## 约定
以下短语翻译约定：

- before you begin  开始之前
- further reading   进阶阅读
- next step         下一步
- understanding What happened 理解原理
- trace 追踪

以下词汇不翻译：

- BookInfo
- Citadel
- HTTP header
- Mixer
- Network Policy 网络策略，如果特指 k8s 中的资源，建议不翻译
- Pilot
- TLS
- egress
- endpoint 端点，建议不翻译
- productpage 示例服务名，不用翻译
- ingress
- ratings 示例服务名，不用翻译
- reviews 示例服务名，不用翻译
- sidecar
- span 分布式追踪中用的词汇

## 格式约定

- 中文标点与英文之间**不需要**加空格
- 中文与数字之间、英文与数字之间都**需要**加空格。
- 出现并列的词请使用中文顿号
- 文章头信息中的`description`部分最后要以标点符号结束，如句号和问号

如果大家对其他词汇有异议可以回复该issue。

**Comment by XiaYinchang** [comment]
建议添加：
policy 策略

**Comment by rootsongjc** [comment]
关于术语部分请参考[Service Mesh术语表](https://github.com/servicemesher/glossary)，本issue近做翻译约定。

**Comment by xionchen** [comment]
Network Policy网络策略，如果特指 k8s 中的资源，建议不翻译
https://kubernetes.io/docs/concepts/services-networking/network-policies/

**Comment by xionchen** [comment]
建议添加
endpoint 端点名，建议不翻译

**Comment by Mr-Linus** [comment]
建议添加
中文标点与英文直接不需要加空格

**Comment by xionchen** [comment]
egress 出口，特指k8s 中的 egress的时候不翻译

**Comment by fleeto** [comment]
聊天室 Bot 中，新增了指令 `search term [term]`，例如：`search term understand`
另外也在官方文档中加入了中文的 [术语和习惯用语](https://preliminary.istio.io/zh/about/contribute/terms/)，二者会保持同步。也欢迎大家提交 PR

**Comment by Mr-Linus** [comment]
建议添加
中文与数字之间、英文与数字之间都需要加空格
出现并列的词请使用顿号

**Comment by rootsongjc** [comment]
@Mr-Linus 已更新到issue里。

**Comment by zy475459736** [comment]
Mixer是否也可以不翻译，保留本身？

**Comment by rootsongjc** [comment]
@zy475459736 这个是Isito本身的组件名称，不需要翻译的。

**Comment by haiker2011** [comment]
Gateway 是保留，还是翻译成网关。

**Comment by rootsongjc** [comment]
@haiker2011 翻译或者保留都可以，保持全文统一即可。

**Comment by haiker2011** [comment]
@rootsongjc OK

**Comment by niceforbear** [comment]
建议添加
you: 您
lagacy：遗留（潜在含义：还在使用但将被重构或升级或废弃, e.g. lagacy service: 遗留服务 lagacy client: 遗留客户端）

**Comment by rootsongjc** [comment]
请直接提交 issue，不用再在此 issue 中回复。
