### ISSUE TITLE
concepts/security/rbac.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#8]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/concepts/security/rbac/index.md) [原文页面](https://preliminary.istio.io/docs/concepts/security/rbac) 

[译文代码](https://github.com/doczhcn/istio/tree/master/docs/concepts/security/rbac.md) [译文页面](http://istio.doczh.cn/docs/concepts/security/rbac.html)

**Comment by rootsongjc** [comment]
原文已转移到 https://preliminary.istio.io/docs/concepts/security/ 本 issue 不再追踪。
