### ISSUE TITLE
concepts/traffic-management/fault-injection.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#9]
[原文代码](https://github.com/istio/istio.github.io/tree/master/content/docs/concepts/traffic-management/fault-injection/index.md) [原文页面](https://preliminary.istio.io/docs/concepts/traffic-management/fault-injection) 

[译文代码](https://github.com/doczhcn/istio/tree/master/docs/concepts/traffic-management/fault-injection.md) [译文页面](http://istio.doczh.cn/docs/concepts/traffic-management/fault-injection.html)

**Comment by rootsongjc** [comment]
该文件已被删除，不再追踪。
