### ISSUE TITLE
about/intro/index.md

### ISSUE THREAD

**Issue by fleeto** [servicemesher/istio-official-translation#95]
[原文代码](https://github.com/istio/istio.github.io/blob/master/content/about/intro/index.md) [原文页面](https://preliminary.istio.io/about/intro/)

**Comment by sillky** [comment]
认领

**Comment by rootsongjc** [comment]
这个issue是因为文章合并导致该issue所在的文件已不存在了，可以关闭该issue，并设置为`stale`状态，不再追踪。
